package sdkgen

import (
	"fmt"
	"net/http"
	"strings"

	"api-playground-hub/pkg/database"

	"github.com/gin-gonic/gin"
)

// GenerateJavaSDK generates standard modern Java 11+ HttpClient code
func GenerateJavaSDK(className string, requests []database.RequestItem) string {
	cleanClass := toPascalCase(className)
	if cleanClass == "" {
		cleanClass = "ApiClient"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`/**
 * Generated by Synqo SDK Generator.
 * Requirements: Java 11+ (java.net.http)
 */

package com.apihub.client;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

public class %s {
    private final String baseUrl;
    private final String authToken;
    private final HttpClient httpClient;

    public %s(String baseUrl, String authToken) {
        this.baseUrl = baseUrl.replaceAll("/+$", "");
        this.authToken = authToken;
        this.httpClient = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(10))
                .build();
    }
`, cleanClass, cleanClass))

	for _, req := range requests {
		funcName := toPascalCase(req.Name)
		urlPath := req.URL
		if strings.HasPrefix(urlPath, "{{baseUrl}}") {
			urlPath = strings.TrimPrefix(urlPath, "{{baseUrl}}")
		}
		if !strings.HasPrefix(urlPath, "/") {
			urlPath = "/" + urlPath
		}

		sb.WriteString(fmt.Sprintf(`
    public String %s(String jsonPayload) throws Exception {
        HttpRequest.Builder builder = HttpRequest.newBuilder()
                .uri(URI.create(this.baseUrl + "%s"))
                .header("Content-Type", "application/json");

        if (this.authToken != null && !this.authToken.isEmpty()) {
            builder.header("Authorization", "Bearer " + this.authToken);
        }

        HttpRequest request = builder.method("%s", HttpRequest.BodyPublishers.ofString(jsonPayload != null ? jsonPayload : ""))
                .build();

        HttpResponse<String> response = this.httpClient.send(request, HttpResponse.BodyHandlers.ofString());
        return response.body();
    }
`, funcName, urlPath, req.Method))
	}

	sb.WriteString("}\n")
	return sb.String()
}

// GenerateCollectionSDK handles the HTTP API request to produce SDK code
func GenerateCollectionSDK(c *gin.Context) {
	collectionID := c.Param("collectionId")
	lang := strings.ToLower(c.DefaultQuery("lang", "typescript"))

	db := database.GetDB()

	var col database.Collection
	if err := db.First(&col, "id = ?", collectionID).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Collection not found"})
		return
	}

	var requests []database.RequestItem
	db.Where("collection_id = ?", collectionID).Order("order_index asc").Find(&requests)

	var code string
	filename := "sdk.txt"

	switch lang {
	case "go", "golang":
		code = GenerateGoSDK(col.Name, requests)
		filename = "client.go"
	case "typescript", "ts", "javascript", "js":
		code = GenerateTypeScriptSDK(col.Name, requests)
		filename = "client.ts"
	case "python", "py":
		code = GeneratePythonSDK(col.Name, requests)
		filename = "client.py"
	case "java":
		code = GenerateJavaSDK(col.Name, requests)
		filename = "ApiClient.java"
	default:
		code = GenerateTypeScriptSDK(col.Name, requests)
		filename = "client.ts"
	}

	c.JSON(http.StatusOK, gin.H{
		"language":       lang,
		"filename":       filename,
		"collectionName": col.Name,
		"requestsCount":  len(requests),
		"code":           code,
	})
}
