package sdkgen

import (
	"fmt"
	"strings"
	"unicode"

	"api-playground-hub/pkg/database"
)

// toPascalCase converts "list-users" or "create_product" into "ListUsers"
func toPascalCase(s string) string {
	var words []string
	curr := ""
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			curr += string(r)
		} else if curr != "" {
			words = append(words, curr)
			curr = ""
		}
	}
	if curr != "" {
		words = append(words, curr)
	}

	res := ""
	for _, w := range words {
		if len(w) > 0 {
			res += strings.ToUpper(w[:1]) + strings.ToLower(w[1:])
		}
	}
	if res == "" {
		res = "Execute"
	}
	return res
}

// GenerateGoSDK generates idiomatic Go SDK client code
func GenerateGoSDK(pkgName string, requests []database.RequestItem) string {
	cleanPkg := strings.ToLower(strings.ReplaceAll(pkgName, " ", ""))
	if cleanPkg == "" {
		cleanPkg = "client"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`// Code generated by Synqo SDK Generator. DO NOT EDIT.
package %s

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// Client represents an API client for %s
type Client struct {
	BaseURL    string
	AuthToken  string
	HTTPClient *http.Client
}

// ClientOption allows configuring the client
type ClientOption func(*Client)

// WithHTTPClient sets a custom HTTP client
func WithHTTPClient(httpClient *http.Client) ClientOption {
	return func(c *Client) {
		c.HTTPClient = httpClient
	}
}

// NewClient initializes a new API client
func NewClient(baseURL, authToken string, opts ...ClientOption) *Client {
	c := &Client{
		BaseURL:   strings.TrimRight(baseURL, "/"),
		AuthToken: authToken,
		HTTPClient: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}
`, cleanPkg, pkgName))

	for _, req := range requests {
		funcName := toPascalCase(req.Name)
		urlPath := req.URL
		if strings.HasPrefix(urlPath, "{{baseUrl}}") {
			urlPath = strings.TrimPrefix(urlPath, "{{baseUrl}}")
		}
		if !strings.HasPrefix(urlPath, "/") {
			urlPath = "/" + urlPath
		}

		hasBody := req.Method == "POST" || req.Method == "PUT" || req.Method == "PATCH"

		if hasBody {
			sb.WriteString(fmt.Sprintf(`
// %s: %s
func (c *Client) %s(ctx context.Context, payload any) ([]byte, error) {
	fullURL := c.BaseURL + "%s"
	var bodyReader io.Reader
	if payload != nil {
		b, err := json.Marshal(payload)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal payload: %%w", err)
		}
		bodyReader = bytes.NewBuffer(b)
	}

	req, err := http.NewRequestWithContext(ctx, "%s", fullURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %%w", err)
	}

	req.Header.Set("Content-Type", "application/json")
	if c.AuthToken != "" {
		req.Header.Set("Authorization", "Bearer "+c.AuthToken)
	}

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %%w", err)
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %%w", err)
	}

	if resp.StatusCode >= 400 {
		return bodyBytes, fmt.Errorf("api error (status %%d): %%s", resp.StatusCode, string(bodyBytes))
	}

	return bodyBytes, nil
}
`, funcName, req.Description, funcName, urlPath, req.Method))
		} else {
			sb.WriteString(fmt.Sprintf(`
// %s: %s
func (c *Client) %s(ctx context.Context) ([]byte, error) {
	fullURL := c.BaseURL + "%s"
	req, err := http.NewRequestWithContext(ctx, "%s", fullURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %%w", err)
	}

	req.Header.Set("Accept", "application/json")
	if c.AuthToken != "" {
		req.Header.Set("Authorization", "Bearer "+c.AuthToken)
	}

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request failed: %%w", err)
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %%w", err)
	}

	if resp.StatusCode >= 400 {
		return bodyBytes, fmt.Errorf("api error (status %%d): %%s", resp.StatusCode, string(bodyBytes))
	}

	return bodyBytes, nil
}
`, funcName, req.Description, funcName, urlPath, req.Method))
		}
	}

	return sb.String()
}
