package sdkgen

import (
	"fmt"
	"strings"
	"unicode"

	"api-playground-hub/pkg/database"
)

// toSnakeCase converts "ListUsers" or "list-users" to "list_users"
func toSnakeCase(s string) string {
	var words []string
	curr := ""
	for _, r := range s {
		if unicode.IsUpper(r) {
			if curr != "" {
				words = append(words, strings.ToLower(curr))
				curr = ""
			}
			curr += string(r)
		} else if unicode.IsLetter(r) || unicode.IsDigit(r) {
			curr += string(r)
		} else if curr != "" {
			words = append(words, strings.ToLower(curr))
			curr = ""
		}
	}
	if curr != "" {
		words = append(words, strings.ToLower(curr))
	}
	if len(words) == 0 {
		return "execute"
	}
	return strings.Join(words, "_")
}

// GeneratePythonSDK generates idiomatic Python client SDK using requests
func GeneratePythonSDK(className string, requests []database.RequestItem) string {
	cleanClass := toPascalCase(className)
	if cleanClass == "" {
		cleanClass = "ApiClient"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`"""
Generated by Synqo SDK Generator.
Dependencies: pip install requests
"""

import requests
from typing import Any, Dict, Optional

class %s:
    """API Client for %s"""

    def __init__(self, base_url: str, token: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self.token = token
        self.session = requests.Session()
        self.session.headers.update({
            "Content-Type": "application/json",
            "Accept": "application/json"
        })
        if self.token:
            self.session.headers.update({"Authorization": f"Bearer {self.token}"})

    def _request(self, method: str, path: str, json_data: Optional[Any] = None) -> Any:
        url = f"{self.base_url}{path}"
        response = self.session.request(method, url, json=json_data)
        response.raise_for_status()
        try:
            return response.json()
        except ValueError:
            return response.text
`, cleanClass, className))

	for _, req := range requests {
		funcName := toSnakeCase(req.Name)
		urlPath := req.URL
		if strings.HasPrefix(urlPath, "{{baseUrl}}") {
			urlPath = strings.TrimPrefix(urlPath, "{{baseUrl}}")
		}
		if !strings.HasPrefix(urlPath, "/") {
			urlPath = "/" + urlPath
		}

		hasBody := req.Method == "POST" || req.Method == "PUT" || req.Method == "PATCH"

		if hasBody {
			sb.WriteString(fmt.Sprintf(`
    def %s(self, payload: Optional[Dict[str, Any]] = None) -> Any:
        """
        %s
        %s
        """
        return self._request("%s", "%s", json_data=payload)
`, funcName, req.Name, req.Description, req.Method, urlPath))
		} else {
			sb.WriteString(fmt.Sprintf(`
    def %s(self) -> Any:
        """
        %s
        %s
        """
        return self._request("%s", "%s")
`, funcName, req.Name, req.Description, req.Method, urlPath))
		}
	}

	return sb.String()
}
