package sdkgen

import (
	"fmt"
	"strings"
	"unicode"

	"api-playground-hub/pkg/database"
)

// toCamelCase converts "ListUsers" or "list_users" into "listUsers"
func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if pascal == "" {
		return "execute"
	}
	r := []rune(pascal)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

// GenerateTypeScriptSDK generates modern TypeScript client SDK
func GenerateTypeScriptSDK(className string, requests []database.RequestItem) string {
	cleanClass := toPascalCase(className)
	if cleanClass == "" {
		cleanClass = "ApiClient"
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`/**
 * Generated by Synqo SDK Generator.
 * Environment: Node.js / Browser (Universal Fetch)
 */

export interface ClientConfig {
  baseUrl: string;
  token?: string;
  headers?: Record<string, string>;
}

export class %s {
  private baseUrl: string;
  private token?: string;
  private headers: Record<string, string>;

  constructor(config: ClientConfig) {
    this.baseUrl = config.baseUrl.replace(/\/+$/, "");
    this.token = config.token;
    this.headers = config.headers || {};
  }

  private async request<T = unknown>(method: string, path: string, body?: unknown): Promise<T> {
    const url = `+"`${this.baseUrl}${path}`"+`;
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      "Accept": "application/json",
      ...this.headers,
    };

    if (this.token) {
      headers["Authorization"] = `+"`Bearer ${this.token}`"+`;
    }

    const response = await fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`+"`API Error [${response.status}]: ${errorText}`"+`);
    }

    const contentType = response.headers.get("content-type");
    if (contentType && contentType.includes("application/json")) {
      return response.json() as Promise<T>;
    }
    return (await response.text()) as unknown as T;
  }
`, cleanClass))

	for _, req := range requests {
		funcName := toCamelCase(req.Name)
		urlPath := req.URL
		if strings.HasPrefix(urlPath, "{{baseUrl}}") {
			urlPath = strings.TrimPrefix(urlPath, "{{baseUrl}}")
		}
		if !strings.HasPrefix(urlPath, "/") {
			urlPath = "/" + urlPath
		}

		hasBody := req.Method == "POST" || req.Method == "PUT" || req.Method == "PATCH"

		if hasBody {
			sb.WriteString(fmt.Sprintf(`
  /**
   * %s
   * @description %s
   */
  async %s<T = unknown, B = unknown>(body?: B): Promise<T> {
    return this.request<T>("%s", "%s", body);
  }
`, req.Name, req.Description, funcName, req.Method, urlPath))
		} else {
			sb.WriteString(fmt.Sprintf(`
  /**
   * %s
   * @description %s
   */
  async %s<T = unknown>(): Promise<T> {
    return this.request<T>("%s", "%s");
  }
`, req.Name, req.Description, funcName, req.Method, urlPath))
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}
